### ISSUE TITLE
File not found: 'pwsh'

### ISSUE THREAD

**Issue by AleF83** [egor-tensin/setup-gcc#1]
Hey,
I run this action on our sef-hosted runner. (https://github.com/evryfs/github-actions-runner)

Got this:

```
Run egor-tensin/setup-gcc@v1
  with:
    platform: x64
    cygwin: 0
    cc: 1
    hardlinks: 0
  env:
    pythonLocation: /home/runner/_work/_tool/Python/3.9.2/x64
    LD_LIBRARY_PATH: /home/runner/_work/_tool/Python/3.9.2/x64/lib
Error: File not found: 'pwsh'
```

**Comment by egor-tensin** [comment]
I wanted to run this action on Linux & Windows, and `pwsh` seemed like [the only choice][1] for writing cross-platform steps (the other one is `bash`, but I don't like the Git bash used on Windows, or whatever).

It says in the docs:

> This is the default shell used on Windows. The PowerShell Core. GitHub appends the extension .ps1 to your script name. If your self-hosted Windows runner does not have PowerShell Core installed, then PowerShell Desktop is used instead.

So I'm afraid you need to install PowerShell Core to use this action.

[1]: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

**Comment by jinlife** [comment]
I'm running this in a self-host ubuntu 18.04 runner too.
It seems your script recognize the self-host as a windows and try to run pwsh
Can we force the os to linux?
@egor-tensin
