### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by MP91** [egor-tensin/setup-gcc#10]
The set-output command is deprecated by GitHub and every workflow using this action gets warning messages on every run.

Would be nice to update this action.

**Comment by SSBMTonberry** [comment]
Just as additional information: `GitHub` redirects to this link to explain the fix: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by egor-tensin** [comment]
Sorry, I was in no fit state to deal with my GitHub Actions for the past year. I'll try to keep up in the future.

Fixed and released.
