### ISSUE TITLE
Support setting the version

### ISSUE THREAD

**Issue by HDembinski** [egor-tensin/setup-gcc#2]
This would be great if you support installing specific versions of gcc.

**Comment by egor-tensin** [comment]
@HDembinski Sorry for the delay. I agree. I'll think about how best to implement it in a practical way.

**Comment by egor-tensin** [comment]
@HDembinski There's now the `version` parameter, which will install the corresponding `g++-VERSION` package. The `ubuntu-toolchain-r/test` PPA is enabled for more GCC versions (although it had always been enabled on hosted runners). For a list of versions currently supported on Bionic & Focal, see README. A CI run that tests all the available versions for those distributions can be found here: https://github.com/egor-tensin/setup-gcc/actions/runs/993536290.
