### ISSUE TITLE
Wishlist: Support for Ubuntu 22.04 (and GCC 12)

### ISSUE THREAD

**Issue by fbriere** [egor-tensin/setup-gcc#5]

**Comment by kenorb** [comment]
The latest version which is installed by the action seems to be `g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`.
On my local I've got `g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0`.
It's way behind.

**Comment by kenorb** [comment]
Related: GH-4.

**Comment by fbriere** [comment]
@kenorb Don't be misled by the `latest` keyword, which actually installs the *default* version within the chosen distribution release (9 in `focal`, 11 in `jammy`).  You can install gcc 11 on 20.04 just fine, but you need to specify the version yourself.

**Comment by fengwang** [comment]
Is it possible to support g++-12 for now? My project has some problem with g++-11, but works fine with g++-12. And I would like to use g++-12 in the workflow.

**Comment by bevanwsjones** [comment]
Is there any movement on this issue? I would really like to move to GCC12

**Comment by egor-tensin** [comment]
Sorry, I was in no fit state to deal with my GitHub Actions for the past year. I'll try to keep up in the future.

Done and released. Jammy is the only Ubuntu version that supports GCC 12 though.
