### ISSUE TITLE
Update v1 to point to the latest v1.2

### ISSUE THREAD

**Issue by kenorb** [egor-tensin/setup-gcc#6]

**Comment by fbriere** [comment]
Don't both `v1` and `v1.2` [tags](https://github.com/egor-tensin/setup-gcc/tags), as well as the `v1` [release](https://github.com/egor-tensin/setup-gcc/releases), all point to the same commit (d04208cef6e985db0830428975fc2ab3f28d89a1) already?

**Comment by kenorb** [comment]
Yes, it is now, thanks. I think it wasn't before.
